language: android
android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - add-on
    - extra
licenses:
    - 'android-sdk-license-.+'
jdk:
    - oraclejdk8
script:
    - ./gradlew \
    :repository:testMockDebugUnitTest :repository:testProdDebugUnitTest :repository:testProdReleaseUnitTest \
    :core:testMockDebugUnitTest :core:testProdDebugUnitTest :core:testProdReleaseUnitTest \
    :base:testMockDebugUnitTest :base:testProdDebugUnitTest :base:testProdReleaseUnitTest \
    :app:testMockDebugUnitTest :app:testProdDebugUnitTest :app:testProdReleaseUnitTest
before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
      - chmod +x ./gradlew
      - yes | sdkmanager "platforms;android-27"
