
language: python

python:
  - "2.7"
  - "3.4"

 
before_install:
  - pip install pytest-cov
  
  

script:
    # Print build info that binary is compiled with.
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_BUILD_NUMBER
    - echo $TRAVIS_REPO_SLUG


 
