version: 2
jobs:
  build:
    branches:
      only:
        - dev
    docker:
      - image: circleci/android:api-27
    steps:
      - run:
          name: Run Tests
          command: ./gradlew test
